config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'students/index'=>'students#index'
  get 'students/new'=>'students#new'
  post 'students' => 'students#create'
  get 'students/:id' => 'students#show',as: 'student'
  root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    def index
        @student = Student.all
    end

    def new
        @student = Student.new
    end

    def create
        student = Student.new(student_params)
        if student.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @student = Student.find(params[:id])
      end
    
      private
      def student_params
        params.require(:student).permit(:name,:profile,:mentor,:grade)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geekkobe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1>GeekKobeman</h1>
<h3>ささやき一覧</h3>
<%= link_to "新規ささやきへ", students_new_path %>
<div class="students-container">
  <% @student.each do |t| %>
    <div class="student">
      <%= t.name %>
      <%= t.profile %>
      <%= t.mentor %>
      <%= t.grade %>
      <%= t.created_at %>

       <%= link_to "詳細へ", student_path(t.id) %>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<h1>GeekKobeman</h1>
<h3>新規ささやき</h3>
<%= form_for @student do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :size => 140 %>
    <%= f.label :profile %>
    <%= f.text_field :profile, :size => 140 %>
    <%= f.label :mentor %>
    <%= f.text_field :mentor, :size => 140 %>
    <%= f.label :grade %>
    <%= f.text_field :grade, :size => 140 %>
  </div>
  <%= f.submit "ささやく" %>
<% end %>

app/views/students/show.html.erb
<h1>GeekKobeman</h1>
<h3>ささやき詳細</h3>
<div class="student">
  <p><%= @student.name %></p>
  <p><%= @student.profile %></p>
  <p><%= @student.mentor %></p>
  <p><%= @student.grade %></p>
  <p><%= @student.created_at %></p>
</div>

<%= link_to "ささやき一覧に戻る", students_index_path %>